//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesView
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime HireDate { get; set; }
        public int WorkedHours { get; set; }
        public string GENDER { get; set; }
        public string Job { get; set; }
        public double PayPerHour { get; set; }
        public string Department { get; set; }
        public double Salary { get; set; }
    }
}
