//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime HireDate { get; set; }
        public int WorkedHours { get; set; }
        public int Gender { get; set; }
        public int Job { get; set; }
        public int Department { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Job Job1 { get; set; }
    }
}
