USE MASTER;

GO

DROP DATABASE IF EXISTS EmployeesDB;

GO

CREATE DATABASE EmployeesDB;

GO

USE EmployeesDB;

GO

-- TABLES

CREATE TABLE Gender(
	Id INT IDENTITY(1, 1) NOT NULL,
	"Name" VARCHAR(255) UNIQUE NOT NULL
);

GO

INSERT INTO Gender
	VALUES
		('Female'),
		('Male');

GO

CREATE TABLE Department(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	"Name" VARCHAR(255) UNIQUE NOT NULL
);

GO

CREATE TABLE Job(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	"Name" VARCHAR(255) UNIQUE NOT NULL
);

GO

CREATE TABLE Employee (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	BirthDate DATE NOT NULL,
	HireDate DATE NOT NULL,
	Salary FLOAT NOT NULL,	
	PerformaceScore FLOAT DEFAULT 0,
	Gender INT FOREIGN KEY REFERENCES Gender(Id) NOT NULL,
	Job INT FOREIGN KEY REFERENCES Job(Id) NOT NULL,
	Department INT FOREIGN KEY REFERENCES Department(Id) NOT NULL

);

GO

-- /TABLES